### PR TITLE
PDP Slideshow Styling Updates

### PR DESCRIPTION
**Pull request by chrismekim**
### Description

- Adjusts styling of slider (built with https://splidejs.com/)
- Removes the buttons and makes it draggable on desktop and mobile
- Changes styling of the slides (no longer centered, takes up full height, adds rounded border radius) 
- **NOTE:** the designs show slideshow images with text. The text will come from the image that the editor creates.
- Added a few to-dos with corresponding Github issues

### Type(s) of changes

- [x] Update to an existing feature

### Motivation for PR

#164 
### How Has This Been Tested?

https://36sy4zsgsplbsjhc-52674822324.shopifypreview.com
View this product for an example of the new types of images that will be added: https://index-space.org/products/anthropocene-copy

### Applicable screenshots:

image
image

### CODE REVIEW

**Comment by chrismekim** [comment]
Pls ignore any themegit previews for now! This github action is not ready yet. 

**Shopify Preview:** https://36sy4zsgsplbsjhc-52674822324.shopifypreview.com
**View this product for an example of the new types of images that will be added:** https://index-space.org/products/anthropocene-copy

**Review by uditdesai — COMMENTED** [review]
First time looking at this so lmk if I'm bringing up anything that's actually intended or not in scope for this PR @chrismekim 

### Desktop
- Maybe changing the cursor on hover of the slider would help let people know that they can interact with it? (`cursor: grab` might be cool?)

### Mobile
- side padding around the product form doesn't match the header above and text below
- There's a slight padding around the slider so when I drag it, I see a off-white line on the sides. Should the slider be full width so there wouldn't be this slight padding around it?

**Reference below**
mobile-ref

**Review by good-idea — APPROVED** [review]
Looks great!

**Review by uditdesai — APPROVED** [review]
Looks great!

**Pull request merged**
