### PR TITLE
Feature/181-186-update-PDP-with-product-state-and-free

### PR DESCRIPTION
**Pull request by uditdesai**
## Description

This PR is an extension of https://github.com/sanctuarycomputer/nunu/pull/183 and it updates the PDP with two main changes:

1. Products that have a price of $0 now say "FREE" on the PDP instead of $0.
2. The add to cart button now has more detail for bookable products and is labelled by the product state and is disabled/enabled accordingly

All labels have been added to the locales so they are easily changeable.

The registration state logic is copied from `product-registration-state.liquid` snippet. The top of the file with Liquid gets quite large though but since all the logic is only needed for the add to cart button, there's no reason to do this logic beforehand or separate it.

I also had to make slight CSS changes to the spacing and width so everything still looks right.

### Type(s) of changes

- [x] New feature
- [x] Update to an existing feature

### Motivation for PR

https://github.com/sanctuarycomputer/nunu/issues/186
https://github.com/sanctuarycomputer/nunu/issues/181

### How Has This Been Tested?

Tested different screen sizes to make sure the different button labels fit.

**Share preview link:** https://wr0fl0mwlaacs4ix-52674822324.shopifypreview.com

In the past bookable product and free product: https://index-space.org/products/disobey-a-playful-guide-to-disobedience-creativity-and-rebellion
Sold out bookable product: https://index-space.org/products/testinjg-sold-out-1
Registration closed bookable product: https://index-space.org/products/testing-registration-closed
Upcoming bookable product: https://index-space.org/products/testing

### Applicable screenshots:

Screen Shot 2021-05-31 at 1 26 59 PM

### Question

All the locales for the button labels also have aria-labels but they're never used in the code? It doesn't seem like the button itself needs a label because it has clear text within it so should these be used elsewhere or removed from the locales? @chrismekim @sepowitz

### CODE REVIEW

**Comment by sepowitz** [comment]
Looks great @uditdesai TY! The one state I'm not sure about is the Registration Closed state on the PDP, mostly because it looks a bit weird in the CTA (too big), maybe we can change it to close for the cta state? Might be worth asking Jake, but I'm sure he would agree or have another suggestion

**Comment by uditdesai** [comment]
> Looks great @uditdesai TY! The one state I'm not sure about is the Registration Closed state on the PDP, mostly because it looks a bit weird in the CTA (too big), maybe we can change it to `Closed` for the cta state? Might be worth asking Jake, but I'm sure he would agree or have another suggestion

Agreed @sepowitz It's too long. Could change it to something like 'Closed' or even keep 'Sold out'.

**Review by chrismekim — APPROVED** [review]
Nice job @uditdesai 💯

**Review by sepowitz — APPROVED** [review]
Love it! TY @uditdesai

**Pull request merged**
